'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import useSWR from 'swr';
import { Lightbulb, RefreshCw } from 'lucide-react';
import { AiMark, Badge, Button, PageHeader, Panel, Segmented, Skeleton, Stars } from '@/components/ui';
import { Funnel, MonthlyBars, RatingDistribution, RatingLine, SentimentStrip, TopicBalance } from '@/components/charts';
import { hours, num } from '@/lib/format';
import { api } from '@/lib/api';

function Metric({ label, value, sub }: { label: string; value: React.ReactNode; sub?: string }) {
  return (
    <div className="px-5 py-4">
      <p className="text-[13px] text-ink-muted">{label}</p>
      <p className="mt-1 font-display text-2xl font-semibold tabular">{value}</p>
      {sub && <p className="mt-0.5 text-xs text-ink-muted">{sub}</p>}
    </div>
  );
}

export default function AnalyticsPage() {
  const router = useRouter();
  const [days, setDays] = useState('0');
  const { data: o } = useSWR('/analytics/reviews');
  const { data: t, isLoading: tLoading } = useSWR(`/analytics/topics?days=${days}`);
  const { data: f } = useSWR('/analytics/requests');
  const { data: ai } = useSWR('/analytics/ai');
  const { data: insights, mutate: mutateInsights } = useSWR('/analytics/insights');
  const [refreshing, setRefreshing] = useState(false);

  const regen = async () => {
    setRefreshing(true);
    try {
      mutateInsights(await api('/analytics/insights?refresh=1'), false);
    } finally {
      setRefreshing(false);
    }
  };

  if (!o) return <><PageHeader title="Analytics" /><Skeleton className="h-96" /></>;
  const maxSvc = Math.max(1, ...(t?.byService || []).map((s: any) => s.count));
  const maxKw = Math.max(1, ...(t?.keywords || []).map((k: any) => k.count));

  return (
    <>
      <PageHeader title="Analytics" subtitle="How your reputation is moving, what customers keep mentioning, and whether review requests are working." />

      <div className="mb-6 grid grid-cols-2 divide-line-soft overflow-hidden rounded-xl2 border border-line-soft bg-white shadow-lift sm:grid-cols-3 sm:divide-x lg:grid-cols-6">
        <Metric label="Total reviews" value={num(o.total)} />
        <Metric label="Average rating" value={<span className="flex items-center gap-2">{o.avgRating.toFixed(2)}<Stars value={o.avgRating} size={12} /></span>} />
        <Metric label="This month" value={num(o.thisMonth)} sub={`${num(o.lastMonth)} last month`} />
        <Metric label="Response rate" value={`${o.responseRate}%`} sub={`${o.unanswered} unanswered`} />
        <Metric label="Average reply time" value={hours(o.avgResponseHours)} />
        <Metric label="Rating this month" value={o.avgRatingThisMonth ?? '—'} />
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <Panel title="New reviews per month"><MonthlyBars series={o.series} /></Panel>
        <Panel title="Overall rating over time">
          <p className="-mt-2 mb-2 text-sm text-ink-muted">Your cumulative Google average at the end of each month.</p>
          <RatingLine series={o.series} height={150} />
        </Panel>
      </div>

      {/* AI insights */}
      <Panel className="mt-6" title={<div className="flex items-center gap-2"><Lightbulb className="h-5 w-5 text-star" /><h2 className="font-display text-[17px] font-semibold">What to do about it</h2></div>} action={<Button size="sm" variant="ghost" onClick={regen} loading={refreshing} icon={<RefreshCw className="h-3.5 w-3.5" />}>Refresh</Button>}>
        {!insights ? <Skeleton className="h-24" /> : !insights.insights?.length ? <p className="text-sm text-ink-muted">Insights appear once there are enough analysed reviews.</p> : (
          <>
            <ul className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
              {insights.insights.map((i: any, k: number) => (
                <li key={k} className="ai-sheen flex flex-col rounded-xl p-4">
                  <Badge tone={i.impact === 'high' ? 'bad' : i.impact === 'medium' ? 'warn' : 'neutral'} className="w-fit">{String(i.impact || 'medium').replace(/^./, (c: string) => c.toUpperCase())} impact</Badge>
                  <p className="mt-3 text-sm text-ink-soft">{i.observation}</p>
                  <p className="mt-2 text-[15px] font-medium leading-snug text-ink">{i.action}</p>
                </li>
              ))}
            </ul>
            <AiMark className="mt-4" label={insights.model === 'heuristic' ? 'Generated by built-in rules' : 'Suggested by AI from your review data — use your judgement'} />
          </>
        )}
      </Panel>

      {/* Themes */}
      <section id="topics" className="mt-10">
        <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="font-display text-xl font-semibold">What customers say</h2>
          <Segmented value={days} onChange={setDays} options={[{ value: '30', label: '30 days' }, { value: '90', label: '90 days' }, { value: '365', label: '12 months' }, { value: '0', label: 'All time' }]} />
        </div>
        <div className={`grid gap-6 transition-opacity lg:grid-cols-[1.3fr_1fr] ${tLoading ? 'opacity-60' : ''}`}>
          <Panel title="Praised and criticised themes">
            {t ? <TopicBalance praised={t.praised} criticized={t.criticized} onSelect={(x) => router.push(`/app/reviews?topic=${encodeURIComponent(x)}`)} /> : <Skeleton className="h-40" />}
            {t && <p className="mt-4 text-xs text-ink-muted">From {t.analyzed} analysed reviews. Select a theme to read those reviews.</p>}
          </Panel>
          <Panel title="Ratings by service">
            {!t?.byService?.length ? <p className="text-sm text-ink-muted">Services are detected when customers mention them by name.</p> : (
              <ul className="space-y-3">
                {t.byService.slice(0, 8).map((s: any) => (
                  <li key={s.service}>
                    <div className="flex items-baseline justify-between text-sm"><span className="font-medium">{s.service}</span><span className="tabular text-ink-muted"><span className="font-medium text-ink">{s.avgRating.toFixed(1)}★</span> · {s.count} mention{s.count > 1 ? 's' : ''}</span></div>
                    <div className="mt-1 h-2 rounded-full bg-line-soft"><div className="h-full rounded-full bg-brand-400" style={{ width: `${(s.count / maxSvc) * 100}%` }} /></div>
                  </li>
                ))}
              </ul>
            )}
          </Panel>
          <Panel title="Ratings & sentiment">
            <RatingDistribution distribution={o.distribution} onSelect={(s) => router.push(`/app/reviews?rating=${s}`)} />
            <div className="mt-6 border-t border-line-soft pt-5"><SentimentStrip sentiment={o.sentiment} /></div>
          </Panel>
          <Panel title="Frequent words">
            <div className="flex flex-wrap gap-2">
              {(t?.keywords || []).map((k: any) => (
                <span key={k.word} className="rounded-full bg-mist px-3 py-1 text-ink-soft" style={{ fontSize: 12 + (k.count / maxKw) * 8 }}>{k.word} <span className="text-xs tabular text-ink-faint">{k.count}</span></span>
              ))}
              {!t?.keywords?.length && <p className="text-sm text-ink-muted">No keywords yet.</p>}
            </div>
          </Panel>
        </div>
      </section>

      {/* Requests + AI */}
      <section className="mt-10 grid gap-6 lg:grid-cols-2">
        <Panel title="Review-request funnel">
          {f ? (
            <>
              <Funnel steps={[{ label: 'Customers with a logged visit', value: f.customersWithVisits }, { label: 'Requests sent', value: f.sent }, { label: 'Opened the link', value: f.clicked }, { label: 'Left a review', value: f.reviewed }]} />
              <p className="mt-4 text-sm text-ink-muted">Conversion: <span className="font-medium text-ink">{f.conversionRate}%</span> of sent requests led to a review we could attribute.</p>
            </>
          ) : <Skeleton className="h-40" />}
        </Panel>
        <Panel title="AI assistance">
          {ai ? (
            <dl className="grid grid-cols-2 gap-x-6 gap-y-5">
              {[['Reviews analysed', ai.analyzed], ['Replies drafted', ai.generated], ['Approved', ai.approved], ['Published', ai.published]].map(([l, v]) => (
                <div key={l as string}><dt className="text-[13px] text-ink-muted">{l}</dt><dd className="mt-0.5 font-display text-2xl font-semibold tabular">{num(v as number)}</dd></div>
              ))}
              <div className="col-span-2 rounded-xl bg-mist px-4 py-3 text-sm text-ink-soft">{ai.published ? <>You edited <span className="font-medium text-ink">{ai.editRate}%</span> of published AI replies before posting.</> : 'No AI replies published yet.'}</div>
            </dl>
          ) : <Skeleton className="h-40" />}
        </Panel>
      </section>
    </>
  );
}
